Getting the Database from Kaggle

In [1]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("vikasukani/parkinsons-disease-data-set")

print("Path to dataset files:", path)

c:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

Downloading to C:\Users\User\.cache\kagglehub\datasets\vikasukani\parkinsons-disease-data-set\1.archive...

100%|██████████| 15.6k/15.6k [00:00<00:00, 203kB/s]

Extracting files...
Path to dataset files: C:\Users\User\.cache\kagglehub\datasets\vikasukani\parkinsons-disease-data-set\versions\1

Importing all Dependencies

In [4]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score

Data Collection and Processing

In [6]:
#Loading the dataset to a pandas DataFrame
parkinsons_data = pd.read_csv(r"C:\Users\User\ML_crush_course\ML_challenges\parkinsons_data.csv")

In [7]:
#getting the first 5 rows of teh dataframe

parkinsons_data.head()

             name  MDVP:Fo(Hz)  MDVP:Fhi(Hz)  ...   spread2        D2       PPE
0  phon_R01_S01_1      119.992       157.302  ...  0.266482  2.301442  0.284654
1  phon_R01_S01_2      122.400       148.650  ...  0.335590  2.486855  0.368674
2  phon_R01_S01_3      116.682       131.111  ...  0.311173  2.342259  0.332634
3  phon_R01_S01_4      116.676       137.871  ...  0.334147  2.405554  0.368975
4  phon_R01_S01_5      116.014       141.781  ...  0.234513  2.332180  0.410335

[5 rows x 24 columns]

Status column in the dataframe gives a information which patients have parkinson's.

1. 0 --> No parkinson's
2. 1 --> Parkinson's

In [8]:
#Getting teh basic info about the dataset
parkinsons_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 195 entries, 0 to 194
Data columns (total 24 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   name              195 non-null    object
 1   MDVP:Fo(Hz)       195 non-null    float64
 2   MDVP:Fhi(Hz)      195 non-null    float64
 3   MDVP:Flo(Hz)      195 non-null    float64
 4   MDVP:Jitter(%)    195 non-null    float64
 5   MDVP:Jitter(Abs)  195 non-null    float64
 6   MDVP:RAP          195 non-null    float64
 7   MDVP:PPQ          195 non-null    float64
 8   Jitter:DDP        195 non-null    float64
 9   MDVP:Shimmer      195 non-null    float64
 10  MDVP:Shimmer(dB)  195 non-null    float64
 11  Shimmer:APQ3      195 non-null    float64
 12  Shimmer:APQ5      195 non-null    float64
 13  MDVP:APQ          195 non-null    float64
 14  Shimmer:DDA       195 non-null    float64
 15  NHR               195 non-null    float64
 16  HNR               195 non-null    float64
 17  status            195 non-null    int64
 18  RPDE              195 non-null    float64
 19  DFA               195 non-null    float64
 20  spread1           195 non-null    float64
 21  spread2           195 non-null    float64
 22  D2                195 non-null    float64
 23  PPE               195 non-null    float64
dtypes: float64(22), int64(1), object(1)
memory usage: 36.7+ KB

In [9]:
#Checking for the missing data

parkinsons_data.isnull().sum()

name                0
MDVP:Fo(Hz)         0
MDVP:Fhi(Hz)        0
MDVP:Flo(Hz)        0
MDVP:Jitter(%)      0
MDVP:Jitter(Abs)    0
MDVP:RAP            0
MDVP:PPQ            0
Jitter:DDP          0
MDVP:Shimmer        0
MDVP:Shimmer(dB)    0
Shimmer:APQ3        0
Shimmer:APQ5        0
MDVP:APQ            0
Shimmer:DDA         0
NHR                 0
HNR                 0
status              0
RPDE                0
DFA                 0
spread1             0
spread2             0
D2                  0
PPE                 0
dtype: int64

In [10]:
#Getting the statistical measures about the data

parkinsons_data.describe()

       MDVP:Fo(Hz)  MDVP:Fhi(Hz)  ...          D2         PPE
count   195.000000    195.000000  ...  195.000000  195.000000
mean    154.228641    197.104918  ...    2.381826    0.206552
std      41.390065     91.491548  ...    0.382799    0.090119
min      88.333000    102.145000  ...    1.423287    0.044539
25%     117.572000    134.862500  ...    2.099125    0.137451
50%     148.790000    175.829000  ...    2.361532    0.194052
75%     182.769000    224.205500  ...    2.636456    0.252980
max     260.105000    592.030000  ...    3.671155    0.527367

[8 rows x 23 columns]

In [25]:
#distribution of traget variable

parkinsons_data["status"].value_counts()

status
1    147
0     48
Name: count, dtype: int64

Labeling the data

In [11]:
X = parkinsons_data.drop(columns=['name', 'status'], axis=1)

Y = parkinsons_data['status']

Standardazing data

In [12]:
scaler = StandardScaler()

In [13]:
scaler.fit(X)

StandardScaler()

In [14]:
scaler.transform(X)

array([[-0.82929965, -0.43616456, -0.95203729, ...,  0.48047686,
        -0.21053082,  0.86888575],
       [-0.77097169, -0.53097409, -0.05772056, ...,  1.31118546,
         0.27507712,  1.80360503],
       [-0.90947638, -0.7231683 , -0.10987483, ...,  1.01768236,
        -0.10362861,  1.40266141],
       ...,
       [ 0.49557839,  0.47010361, -0.96839309, ..., -0.81807931,
         0.78033848, -0.83241014],
       [ 1.07876114,  2.19004398, -0.95417967, ..., -0.22906571,
        -0.63700298, -0.92610456],
       [ 1.45481664,  0.69224632, -0.88348115, ..., -0.43085284,
         0.45480231, -0.64505466]], shape=(195, 22))

In [15]:
print(X)

     MDVP:Fo(Hz)  MDVP:Fhi(Hz)  MDVP:Flo(Hz)  ...   spread2        D2       PPE
0        119.992       157.302        74.997  ...  0.266482  2.301442  0.284654
1        122.400       148.650       113.819  ...  0.335590  2.486855  0.368674
2        116.682       131.111       111.555  ...  0.311173  2.342259  0.332634
3        116.676       137.871       111.366  ...  0.334147  2.405554  0.368975
4        116.014       141.781       110.655  ...  0.234513  2.332180  0.410335
..           ...           ...           ...  ...       ...       ...       ...
190      174.188       230.978        94.261  ...  0.121952  2.657476  0.133050
191      209.516       253.017        89.488  ...  0.129303  2.784312  0.168895
192      174.688       240.005        74.287  ...  0.158453  2.679772  0.131728
193      198.764       396.961        74.904  ...  0.207454  2.138608  0.123306
194      214.289       260.277        77.973  ...  0.190667  2.555477  0.148569

[195 rows x 22 columns]

Splitting data into training and test data

In [19]:
X_train, X_test, Y_train, Y_test= train_test_split(
    X, 
    Y,
    train_size =0.2,
    stratify=Y,
    random_state=2
)

In [20]:
print(X_train.shape, X_test.shape, Y_train.shape, Y_test.shape)

(39, 22) (156, 22) (39,) (156,)

Training data

In [21]:
model = SVC(kernel='linear')

In [22]:
model.fit(X_train, Y_train)

SVC(kernel='linear')

Evaluating the data

In [23]:
#Checking the accuracy score on the training data
trainin_prediction_data = model.predict(X_train)

accuracy_trainin_data = accuracy_score(trainin_prediction_data, Y_train)

print("Accuracy score of the training data: ", accuracy_trainin_data)

Accuracy score of the training data:  0.8717948717948718

In [24]:
#Checking the accuracy score on the test data

test_prediction_data = model.predict(X_test)

accuracy_test_data = accuracy_score(test_prediction_data, Y_test)

print("Accuracy score of the test data: ", accuracy_test_data)

Accuracy score of the test data:  0.8461538461538461

Building Predcitive system

In [26]:
input_data = (91.90400,115.87100,86.29200,0.00540,0.00006,0.00281,0.00336,0.00844,0.02752,0.24900,0.01424,0.01641,0.02214,0.04272,0.01141,21.41400,0.583390,0.792520,-4.960234,0.363566,2.642476,0.275931)

In [27]:
input_data_as_numpy_array = np.asarray(input_data)

In [28]:
reshaped_input_data = input_data_as_numpy_array.reshape(1,-1)

In [29]:
prediction = model.predict(reshaped_input_data)

c:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but SVC was fitted with feature names
  warnings.warn(

In [30]:
if prediction[0] == 0:
    print("The person does not have Parkinson's disease")
else:  
    print("The person has Parkinson's disease")

The person has Parkinson's disease